# Generated by Django 3.1.2 on 2020-10-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningMaterial', '0003_auto_20201003_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='title',
            field=models.CharField(default='Note', max_length=80),
        ),
    ]
