# Generated by Django 3.1.2 on 2020-10-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningMaterial', '0011_auto_20201004_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blurb',
            name='blurbText',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='blurb',
            name='fromLink',
            field=models.URLField(max_length=600, null=True),
        ),
    ]
